name: Build Docker Image

on:
    push:
     branches:
     master
       
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Docker
      uses: docker/setup-buildx-action@v1

    - name: Build Docker Image
      run: docker build -t task-manager:latest .

      - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
      registry: docker.io
        username: ${{ secrets.DOCKER_HUB_EMAIL }}
        password: ${{ secrets.DOCKER_HUB_PASSWORD}}
        repository: franknnabugo/frank_nnabugo

    - name: Push Docker Image
      run: docker push task-manager:latest
